### ISSUE TITLE
Not working for windows

### ISSUE THREAD

**Issue by robiwano** [zaf/resample#1]
```
# github.com/zaf/resample
exec: "gcc": executable file not found in %PATH%

```
Perhaps add this in the Readme file. Although, even better, would be to get it working for Windows :)

**Comment by zaf** [comment]
Copying from here: https://github.com/golang/go/wiki/cgo

> In order to use cgo on Windows, you'll also need to first install a gcc compiler (for instance, mingw-w64) and have gcc.exe (etc.) in your PATH environment variable before compiling with cgo will work.
